version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'
  customer:
    image: customer/customer:1.0
    build: Customer
    depends_on:
      - rabbitmq
    ports:
      - "5100:5100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
  contract:
    image: contract/contract:1.0
    build: Contract
    depends_on:
      - rabbitmq
    ports:
      - "5200:5200"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  rabbitmq_data:
    driver: local